I18n.en =
  menu:
    schema: "Sxem"
    new: "Yeni ..."
    load: "Yüklə ..."
    save: "Saxla"
    save_as: "Fərqli saxla ..."
    templates: "Şablonlar ..."
    properties: "Xüsusiyyətlər ..."
    share: "Paylaş ..."
    import: "İdxal et ..."
    edit: "Düzəlt"
    undo: "Geri qaytar"
    redo: "Yenidən et"
    select_all: "Hamısını seç"
    select_none: "Heç birini seçmə"
    delete_selected: "Seçiləni sil"
    insert: "Daxil et"
    table: "Table"
    note: "Qeyd"
    view: "Görünüş"
    show_minimap: "Xəritəni Göstər"
    hide_minimap: "Xəritəni Gizlət"
    show_sidebar: "Yan Paneli Göstər"
    hide_sidebar: "Yan Paneli Gizlət"
    show_grid: "Grid-i göstər"
    hide_grid: "Grid-i gizlət"
    sort_items: "Elementləri Sırala"
    linetype: "Xətt tipi"
    bezier: "Bezier"
    cornered: "Künclü"
    options: "Ayarlar ..."
    export: "İxrac et"
    sql: "Sql ..."
    image: "Şəkil ..."
    help: "Kömək"
    index: "İndeks"
    changes: "Dəyişikliklər"
    shortcuts: "Klaviatura qısayolları"
    feedback: "Əlaqə"
    about: "Haqqında"
    guest: "Qonaq"
    login: "Giriş"
    logout: "Çıxış"
    settings: "Ayarlar"
  panel:
    history: "Keçmiş"
    last_versions_label: "Bu Sxemin son 10 versiyası:"
    properties: "Xüsusiyyətlər"
    properties_schema_name: "Sxemin adı:"
    properties_database: "Məlumat bazası:"
    comments: "Şərhlər"
    comment_placeholder: "Şərhinizi bura daxil edin"
    send: "Göndər"
  dialog:
    new_schema: "Yeni Sxem"
    new_schema_title: "Başlıq"
    new_schema_database: "Məlumat Bazası"
    new_schema_type_info: """Ümumi databazanı seçmək sizə bütün databazalar üçün SQL yaratmağa imkan verir ; bu seçim ancaq "ümumi" databazalara şamil olunur."""
    new_schema_create_new: "Yeni Sxem yarat"
    load_schema: "Yüklə"
    load_schema_your_schemas: "Sənin sxemlərin:"
    load_schema_schema_name: "Sxemin adı"
    load_schema_database: "Məlumat Bazası"
    load_schema_last_save: "Son saxlanılan"
    load_schema_shared_with_you: "Səninlə paylaşılan sxemlər:"
    load_schema_owner: "İstifadəçi"
    load_schema_no_schemas: "Hələ heç bir sxemi saxlamamısan"
    load_schema_no_shared_schemas: "Səninlə paylaşılan sxem yoxdur"
    saveas: "Fərqli Saxla"
    saveas_title: "Başlıq"
    saveas_button: "Fərqli saxla"
    templates: "Şablonlar"
    templates_schema_name: "Sxem adı"
    templates_database: "Məlumat Bazası"
    templates_description: "Açıqlama"
    properties: "Sxemin Xassələri"
    properties_title: "Başlıq"
    properties_publish: "Şablon olaraq paylaş"
    properties_template_info: "(Şablonları bütün istifadəçilər görə bilər)"
    properties_delete_schema: "Sxemi sil"
    properties_delete_alert: "(Bu sxemi və ona aid şərhlər tamamiylə silinəcək)"
    properties_save: "Dəyişiklikləri saxla"
    share: "Paylaş"
    share_info: "Sxemi ən çox 5 istifadəçi ilə paylaşa bilərsən"
    share_email: "E-poçt"
    share_access: "Giriş"
    share_read_only: "Anaq oxumağa"
    share_read_write: "Oxumağa və yazmağa"
    share_send_email: "E-poçtla dəvət göndər"
    share_invite_button: "Dəvət et"
    share_collaborators: "Əməkdaşlar:"
    import: "SQL-i idxal et"
    login_email: "E-poçt"
    login_password: "Şifrə"
    login_button: "Giriş"
    login_forgot_password: "Şifrəmi Unutmuşam"
    options: "Ayarlar"
    options_line_colors: "Xətt rəngləri"
    options_invert_line_direction: "Bağlantı xətlərini tərs çevir"
    options_show_fk_icon: "Xarici açar işarəsi"
    options_show_ai_icon: "Avtomatik artırma işarəsi"
    options_show_not_null_icon: "Null işarəsi"
    options_show_default_values: "Varsayılan dəyərləri göstər"
    options_language: "Dil"
    options_save_changes: "Dəyişiklikləri saxla"
    export_sql: "SQL-i ixrac et"
    export_sql_generate: "SQL-yarat"
    export_sql_download: "SQL faylın ednir"
    export_image: "Şəkili ixrac et"
    export_image_zoomin: "Yaxınlaşdır"
    export_image_zoomout: "Uzarlaşdır"
    export_image_reset: "Sıfırla"
    export_image_open_in_new_tab: "Şəkili yeni pəncərədən aç"
    help: "Kömək"
    shortcuts: "Klaviatura qısayolları"
    help_changelog: "Dəyişikliklər"
    feedback: "Geri Bildiriş"
    feedback_type: "Geri Bildiriş tipi"
    feedback_bug: "Xəta bildir"
    feedback_feature: "Yeni xüsusiyyət tələbi"
    feedback_help: "Kömək"
    feedback_other: "Digər"
    feedback_message: "Mesaj"
    feedback_button: "Geri Bildiriş göndər"
    about: "dbdesigner.net haqqında"
    user_settings: "İstifacəçi ayarları"
    user_settings_username: "İstifadəçi adı"
    user_settings_email: "E-poçt"
    user_settings_save: "Dəyişiklikləri saxla"
    login: "Giriş et"
    close: "Bağla"
    back: "Geri"
    dirty_schema_confirmation: "Saxlanmamış dəyişikliklər var!"
    dirty_schema_confirmation_message: "Sənin sxemində saxlanılmamış dəyişikliklər var, dəyişiklikləri saxlamaq istəyirsən?"
    dirty_schema_confirmation_save_changes_button: "Dəyişikliklərimi saxla"
    dirty_schema_confirmation_discard_changes_and_continue_button: "Dəyişikliklərimi saxlama"
    dirty_schema_confirmation_cancel_button: "Ləğv et"
  designer:
    save_note_edit: "Saxla"
    cancel_note_edit: "Ləğv et"
    delete_note: "Sil"
    table_name: "Cədvəl Adı"
    table_comment: "Cədvəl şərhi"
    table_save: "Saxla"
    table_cancel: "Ləğv et"
    table_delete: "Cədvəli sil"
    table_clone: "Cədvəli klonla"
    table_add_field: "Sahə əlavə et"
    field_name: "Ad"
    field_type: "Tip"
    field_size: "Sahə"
    field_default: "Varsayılan"
    field_unique: "Unikal"
    field_allow_nulls: "Null-lara icazə verən sahə"
    field_autoincrement: "Avtomatik artan"
    field_primary_key: "Birinci Açar"
    field_foreign_key: "Xarici Açar"
    field_save: "Saxla"
    field_update: "Yenilə"
    field_cancel: "Ləğv et"
    field_delete: "Sahəni Sil"
    field_delete_alert: "Bu sahəni silmək istədiyinə əminsən?\n(gələn dəfə təsdiq etmədən silmək üçün SHIFT düyməsini basılı saxlaya bilərsən)"
    field_ref_table: "İstinad cədvəli"
    field_ref_field: "İstinad sahəsi"
  alerts:
    delete_schema: "Bu sxemi silmək istədiyinə əminsən?"
    server_error: "Server xətası baş verdi"
    schema_owner_error: "Bu prosesi yalnız sxemin sahibi yerinə yetirə bilər"
    login_to_use_this_function: "Bu funkisyanı istifadə etmək üçün giriş etməlisən"
