I18n.en =
  menu:
    schema: "Sxem"
    new: "Yeni ..."
    load: "Yüklə ..."
    save: "Yadda Saxla"
    save_as: "Fərqli saxla ..."
    templates: "Şablonlar ..."
    properties: "Xüsusiyyətlər ..."
    share: "Paylaş ..."
    import: "İdxal et ..."
    edit: "Düzəlt"
    undo: "Geri qaytar"
    redo: "Yenidən et"
    select_all: "Hamısını seç"
    select_none: "Heç birini seçmə"
    delete_selected: "Seçiləni sil"
    insert: "Daxil et"
    table: "Table"
    note: "Qeyd"
    view: "View"
    show_minimap: "Show Minimap"
    hide_minimap: "Hide Minimap"
    show_sidebar: "Show Sidebar"
    hide_sidebar: "Hide Sidebar"
    show_grid: "Show Grid"
    hide_grid: "Hide Grid"
    sort_items: "Sort Items"
    linetype: "Line Type"
    bezier: "Bezier"
    cornered: "Cornered"
    options: "Options ..."
    export: "Export"
    sql: "Sql ..."
    image: "Image ..."
    help: "Kömək"
    index: "Index"
    changes: "Dəyişikliklər"
    shortcuts: "Keyboard Shortcuts"
    feedback: "Feedback"
    about: "Haqqında"
    guest: "Qonaq"
    login: "Giriş"
    logout: "Çıxış"
    settings: "Settings"
  panel:
    history: "Keçmiş"
    last_versions_label: "Last 10 versions of this schema:"
    properties: "Properties"
    properties_schema_name: "Schema Name:"
    properties_database: "Məlumat bazası:"
    comments: "Şərhlər"
    comment_placeholder: "Şərhinizi bura daxil edin"
    send: "Göndər"
  dialog:
    new_schema: "New Schema"
    new_schema_title: "Title"
    new_schema_database: "Database"
    new_schema_type_info: """Selecting the "generic" database type will allow you to generate SQL for all the databases; but you will only have access to the generic datatypes."""
    new_schema_create_new: "Create New Schema"
    load_schema: "Load Schema"
    load_schema_your_schemas: "Your Schemas:"
    load_schema_schema_name: "Schema Name"
    load_schema_database: "Database"
    load_schema_last_save: "Last Save"
    load_schema_shared_with_you: "Schemas shared with you:"
    load_schema_owner: "Owner"
    load_schema_no_schemas: "You haven't saved any schemas"
    load_schema_no_shared_schemas: "There are no schemas shared with you"
    saveas: "Save As"
    saveas_title: "Başlıq"
    saveas_button: "Save As"
    templates: "Templates"
    templates_schema_name: "Schema Name"
    templates_database: "Database"
    templates_description: "Description"
    properties: "Schema Properties"
    properties_title: "Title"
    properties_publish: "Publish as template"
    properties_template_info: "(Templates are visible to every user)"
    properties_delete_schema: "Delete Schema"
    properties_delete_alert: "(You will permanently delete this schema and all associated comments)"
    properties_save: "Save Changes"
    share: "Share"
    share_info: "You can share your schema with up to 5 users"
    share_email: "E-mail"
    share_access: "Access"
    share_read_only: "Read only"
    share_read_write: "Read and write"
    share_send_email: "Send invitation e-mail"
    share_invite_button: "Invite"
    share_collaborators: "Collaborators:"
    import: "Import Sql"
    login_email: "E-mail"
    login_password: "Şifrə"
    login_button: "Giriş"
    login_forgot_password: "Şifrəmi Unutmuşam"
    options: "Parametirlər"
    options_line_colors: "Line Colors"
    options_invert_line_direction: "Invert line direction"
    options_show_fk_icon: "Show Foreign Key Icon"
    options_show_ai_icon: "Show Auto Increment Icon"
    options_show_not_null_icon: "Show Not Null icon"
    options_show_default_values: "Show Default Values"
    options_language: "Language"
    options_save_changes: "Save Changes"
    export_sql: "Export SQL"
    export_sql_generate: "Generate SQL"
    export_sql_download: "SQL faylın ednir"
    export_image: "Export Image"
    export_image_zoomin: "Zoom in"
    export_image_zoomout: "Zoom out"
    export_image_reset: "Reset"
    export_image_open_in_new_tab: "Open image in new tab"
    help: "Kömək"
    shortcuts: "Keyboard Shortcuts"
    help_changelog: "Changes"
    feedback: "Feedback"
    feedback_type: "Feedback Type"
    feedback_bug: "Bug report"
    feedback_feature: "Feature Request"
    feedback_help: "Kömək"
    feedback_other: "Other"
    feedback_message: "Mesaj"
    feedback_button: "Send Feedback"
    about: "About dbdesigner.net"
    user_settings: "İstifacəçi parametirləri"
    user_settings_username: "Username"
    user_settings_email: "E-mail"
    user_settings_save: "Save Changes"
    login: "Giriş et"
    close: "Bağla"
    back: "Geri"
    dirty_schema_confirmation: "Unsaved changes!"
    dirty_schema_confirmation_message: "You have unsaved changes in your schema, would you like to save it?"
    dirty_schema_confirmation_save_changes_button: "Save changes"
    dirty_schema_confirmation_discard_changes_and_continue_button: "Discard changes"
    dirty_schema_confirmation_cancel_button: "Ləğv et"
  designer:
    save_note_edit: "Yadda Saxla"
    cancel_note_edit: "Ləğv et"
    delete_note: "Sil"
    table_name: "Table Name"
    table_comment: "Table Comment"
    table_save: "Yadda saxla"
    table_cancel: "Ləğv et"
    table_delete: "Cədvəli sil"
    table_clone: "Cədvəli klonla"
    table_add_field: "Sahə əlavə et"
    field_name: "Ad"
    field_type: "Type"
    field_size: "Size"
    field_default: "Default"
    field_unique: "Unique"
    field_allow_nulls: "Allow nulls"
    field_autoincrement: "Auto Increment"
    field_primary_key: "Primary Key"
    field_foreign_key: "Foreign Key"
    field_save: "Yadda Saxla"
    field_update: "Yenilə"
    field_cancel: "Ləğv et"
    field_delete: "Delete Field"
    field_delete_alert: "Are you sure you want to delete this field?\n(hold shift to delete without confirmation)"
    field_ref_table: "Ref. Table"
    field_ref_field: "Ref. Field"
  alerts:
    delete_schema: "Bu sxemi silmək istədiyinə əminsən?"
    server_error: "Server xətası baş verdi"
    schema_owner_error: "Bu prosesi yalnız sxema sahibi yerinə yetirə bilər"
    login_to_use_this_function: "Bu funkisyanı istifadə etmək üçün giriş etləsiniz"
